train: True
batch_size: 128
epochs: 20
eval_every_n_epochs: 2
log_every_n_steps: 200
learning_rate: 4e-4
weight_decay: 1e-6
dset: shapenet
sparse_model: False

model:
  out_dim: 512
  use_voxel: True
  tri_modal: False
  num_images: 6
  image_cnn: 'resnet18'
  pretraining: True
  vocab_size: 3588

dataset:
  num_workers: 7
  train_json_file: 'datasets/text2shape-data/shapenet/train_map.jsonl'
  val_json_file: 'datasets/text2shape-data/shapenet/val_map.jsonl'
  test_json_file: 'datasets/text2shape-data/shapenet/test_map.jsonl'
  image_size: 128
  voxel_size: 64
  root_npz_file: './datasets/all_npz/'

loss:
  temperature: 0.1
  alpha_weight: 0.25

